from PySide6.QtWidgets import QCheckBox, QComboBox, QFileDialog, QFormLayout, QHBoxLayout, QLabel, QLineEdit, QPushButton, QVBoxLayout, QWidget

class SingleVideoPage(QWidget):
    def __init__(self, settings, submit):
        super().__init__(); self.settings = settings; self.submit = submit; layout = QVBoxLayout(self); title = QLabel("Single Video"); title.setObjectName("PageTitle"); layout.addWidget(title); self.url = QLineEdit(); self.url.setPlaceholderText("https://www.youtube.com/watch?v=..."); layout.addWidget(QLabel("Video URL")); layout.addWidget(self.url); form = QFormLayout(); self.quality = QComboBox(); self.quality.addItems(["240p SD (MP4)","360p SD (MP4)","480p SD (MP4)","720p HD (MP4)","1080p Full HD (MP4)","2K Quad HD (1440p MP4)","4K Ultra HD (2160p MP4)","Original Quality", "MP3 Audio (128 kbps)","MP3 Audio (320 kbps)"]); self.quality.setCurrentText(settings["default_quality"]); form.addRow("Quality", self.quality); folder_row = QHBoxLayout(); self.folder = QLineEdit(settings["default_folder"]); folder_row.addWidget(self.folder); choose = QPushButton("Change"); choose.clicked.connect(self.choose_folder); folder_row.addWidget(choose); form.addRow("Save location", folder_row); layout.addLayout(form); options = QHBoxLayout(); self.subtitles = QCheckBox("Subtitles"); self.subtitles.setChecked(settings["subtitles"]); self.thumbnail = QCheckBox("Thumbnail"); options.addWidget(self.subtitles); options.addWidget(self.thumbnail); options.addStretch(); layout.addLayout(options); download = QPushButton("Download Video"); download.setObjectName("Primary"); download.clicked.connect(self.download); layout.addWidget(download); self.info = QLabel("Metadata will appear here after URL inspection."); self.info.setObjectName("Muted"); layout.addWidget(self.info); layout.addStretch()
    def choose_folder(self):
        value = QFileDialog.getExistingDirectory(self, "Select download folder", self.folder.text())
        if value: self.folder.setText(value)
    def download(self): self.submit(self.url.text().strip(), self.quality.currentText(), self.folder.text(), self.subtitles.isChecked(), self.thumbnail.isChecked())
